export const APP_NAME = "simkl-new-episodes-addon";
export const APP_VERSION = "1.4.0";
export const CATALOG_ID = "simkl-new-anime-episodes";
export const CATALOG_NAME = "My Anime Up Next · Simkl";
export const ADDON_ID = "community.simkl.new-anime-episodes";
export const SIMKL_API_BASE = "https://api.simkl.com";
export const SIMKL_CALENDAR_BASE = "https://data.simkl.in/calendar/v2";
export const SIMKL_CALENDAR_URL = `${SIMKL_CALENDAR_BASE}/anime.json`;
export const DEFAULT_MAX_ITEMS = 50;
